---
include:
  - board: cosmos_lemon_wireless
    shield: cosmotyl_left
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: cosmos_lemon_wireless
    shield: cosmotyl_right
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y
