CONFIG_SPI=y

# RGB underglow configuration
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_BOARD_COMPAT=y
# CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# CONFIG_ZMK_SETTINGS_RESET_ON_START=y
CONFIG_BT_CTLR_PHY_2M=n

# zmk mouse emulation for trackball/trackpad
CONFIG_ZMK_POINTING=n

# encoder support
CONFIG_EC11=n
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=n
