manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: vzhny
      url-base: https://github.com/vzhny

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 268b1b1e82150460f00fd701bcd08583d5c75d29
      import: app/west.yml
    # - name: zmk
    #   remote: rianadon
    #   revision: 4fc05c26b8faa35081282d58abc84fb6bd1b52bd
    #   import: app/west.yml

    - name: zmk-unicode
      remote: urob
      revision: 5f458b6f1fd8ca83f4aba793c2a64916522507e9

    - name: zmk-auto-layer
      remote: urob
      revision: 62c201934711369d50a28df12e1d055d05cb6460

    - name: zmk-helpers
      remote: urob
      revision: 4c71f803db34f5b888a1d09ef699e8e58d03f393

    - name: zmk-leader-key
      remote: urob
      revision: 43029f6fb950dec382774e60c6bcc020a906c942

  self:
    path: config
    import: deps.yml

# manifest:
#   remotes:
#     - name: zmkfirmware
#       url-base: https://github.com/zmkfirmware
#     - name: rianadon
#       url-base: https://github.com/rianadon
#     - name: urob
#       url-base: https://github.com/urob
#
#   projects:
#     - name: zmk
#       remote: rianadon
#       revision: 4fc05c26b8faa35081282d58abc84fb6bd1b52bd
#       import: app/west.yml
#
#     - name: zmk-unicode
#       remote: urob
#       revision: v0.3
#
#     - name: zmk-helpers
#       remote: urob
#       revision: v0.3
#
#     - name: zmk-leader-key
#       remote: urob
#       revision: v0.3
#
#   self:
#     path: config
